#!/bin/bash

################################################################################
# Matrix Configuration Verification Script
# Checks all configuration files for common issues before deployment
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

ERRORS=0
WARNINGS=0

echo -e "${BLUE}=================================${NC}"
echo -e "${BLUE}Matrix Configuration Verification${NC}"
echo -e "${BLUE}=================================${NC}\n"

# Check if files exist
check_file_exists() {
    if [[ -f "$1" ]]; then
        echo -e "${GREEN}✓${NC} Found: $1"
        return 0
    else
        echo -e "${RED}✗${NC} Missing: $1"
        ((ERRORS++))
        return 1
    fi
}

# Check for placeholder values
check_placeholder() {
    local file=$1
    local pattern=$2
    local description=$3

    if grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${YELLOW}⚠${NC}  $description in $file"
        echo -e "    ${YELLOW}Found: $(grep "$pattern" "$file" | head -1 | xargs)${NC}"
        ((WARNINGS++))
        return 1
    else
        echo -e "${GREEN}✓${NC} $description properly configured"
        return 0
    fi
}

echo -e "${BLUE}1. Checking required files...${NC}"
check_file_exists "docker-compose.yml"
check_file_exists "tuwunel.toml"
check_file_exists "Caddyfile"
check_file_exists "coturn.conf"
check_file_exists "element-config.json"
check_file_exists "wellknown/matrix/server"
check_file_exists "wellknown/matrix/client"
check_file_exists "setup.sh"
check_file_exists "firewall.sh"

echo -e "\n${BLUE}2. Checking Tuwunel configuration...${NC}"

# Check if tuwunel.toml has proper address
if grep -q 'address = "0.0.0.0"' tuwunel.toml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Tuwunel listening on all interfaces (0.0.0.0)"
elif grep -q 'address = \["127.0.0.1"' tuwunel.toml 2>/dev/null; then
    echo -e "${RED}✗${NC} ERROR: Tuwunel only listening on localhost - Caddy won't be able to connect!"
    echo -e "   Fix: Change address to \"0.0.0.0\" in tuwunel.toml"
    ((ERRORS++))
else
    echo -e "${YELLOW}⚠${NC}  Could not determine Tuwunel listen address"
    ((WARNINGS++))
fi

# Check registration token
if grep -q 'registration_token = "PLACEHOLDER_REGISTRATION_TOKEN"' tuwunel.toml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Registration token placeholder present (will be generated by setup.sh)"
elif grep -q 'registration_token = "[0-9a-f]\{64\}"' tuwunel.toml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Registration token already configured"
else
    echo -e "${RED}✗${NC} Registration token not found or invalid format"
    ((ERRORS++))
fi

# Check server name
if grep -q 'server_name = "YOUR_DOMAIN"' tuwunel.toml 2>/dev/null; then
    echo -e "${YELLOW}⚠${NC} Server name set to YOUR_DOMAIN placeholder — must be customized before setup"
else
    echo -e "${YELLOW}⚠${NC}  Server name not found or incorrect"
    ((WARNINGS++))
fi

echo -e "\n${BLUE}3. Checking Coturn configuration...${NC}"

# Check TURN secret
if grep -q 'static-auth-secret=PLACEHOLDER_TURN_SECRET' coturn.conf 2>/dev/null; then
    echo -e "${GREEN}✓${NC} TURN secret placeholder present (will be generated by setup.sh)"
elif grep -q 'static-auth-secret=[0-9a-f]\{64\}' coturn.conf 2>/dev/null; then
    echo -e "${GREEN}✓${NC} TURN shared secret already configured"
else
    echo -e "${RED}✗${NC} TURN shared secret not found or invalid format"
    ((ERRORS++))
fi

# Check external IPs
if grep -q 'external-ip=YOUR_IPV4' coturn.conf 2>/dev/null; then
    echo -e "${YELLOW}⚠${NC} External IPv4 set to YOUR_IPV4 placeholder — must be customized before setup"
else
    echo -e "${RED}✗${NC} External IPv4 not found"
    ((ERRORS++))
fi

if grep -q '^external-ip=YOUR_IPV6' coturn.conf 2>/dev/null; then
    echo -e "${YELLOW}⚠${NC} External IPv6 set to YOUR_IPV6 placeholder — must be customized before setup"
else
    echo -e "${YELLOW}⚠${NC}  External IPv6 not active (commented out)"
    ((WARNINGS++))
fi

# Check STUN amplification protection
if grep -q '^no-stun' coturn.conf 2>/dev/null; then
    echo -e "${GREEN}✓${NC} STUN disabled (amplification protection)"
else
    echo -e "${RED}✗${NC} STUN not disabled — vulnerable to amplification attacks"
    ((ERRORS++))
fi

echo -e "\n${BLUE}4. Checking Docker Compose...${NC}"

# Check for required services
for service in tuwunel caddy coturn element; do
    if grep -q "  $service:" docker-compose.yml 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Service defined: $service"
    else
        echo -e "${RED}✗${NC} Service missing: $service"
        ((ERRORS++))
    fi
done

# Check network configuration
if grep -q "network_mode: host" docker-compose.yml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Coturn using host networking (required for TURN)"
else
    echo -e "${RED}✗${NC} Coturn not using host networking - TURN may not work"
    ((ERRORS++))
fi

echo -e "\n${BLUE}5. Checking Caddy configuration...${NC}"

# Check if Caddy proxies to tuwunel
if grep -q "reverse_proxy tuwunel:8008" Caddyfile 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Caddy configured to proxy to Tuwunel"
else
    echo -e "${RED}✗${NC} Caddy not configured to proxy to Tuwunel"
    ((ERRORS++))
fi

# Check well-known endpoints
if grep -q "/.well-known/matrix/" Caddyfile 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Well-known endpoints configured"
else
    echo -e "${YELLOW}⚠${NC}  Well-known endpoints not found in Caddyfile"
    ((WARNINGS++))
fi

# Check federation port
if grep -q "YOUR_DOMAIN:8448" Caddyfile 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Federation port (8448) configured (with YOUR_DOMAIN placeholder)"
else
    echo -e "${YELLOW}⚠${NC}  Federation port configuration not found"
    ((WARNINGS++))
fi

echo -e "\n${BLUE}6. Checking well-known files...${NC}"

# Check server delegation
if [[ -f "wellknown/matrix/server" ]]; then
    if grep -q '"m.server"' wellknown/matrix/server 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Server delegation configured"
    else
        echo -e "${RED}✗${NC} Server delegation file malformed"
        ((ERRORS++))
    fi
fi

# Check client discovery
if [[ -f "wellknown/matrix/client" ]]; then
    if grep -q '"m.homeserver"' wellknown/matrix/client 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Client discovery configured"
    else
        echo -e "${RED}✗${NC} Client discovery file malformed"
        ((ERRORS++))
    fi
fi

echo -e "\n${BLUE}7. Checking Element Web configuration...${NC}"

if [[ -f "element-config.json" ]]; then
    if grep -q '"base_url": "https://YOUR_DOMAIN"' element-config.json 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Element configured (with YOUR_DOMAIN placeholder)"
    else
        echo -e "${YELLOW}⚠${NC}  Element base_url not found or incorrect"
        ((WARNINGS++))
    fi

    if grep -q '"element_call"' element-config.json 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Element Call configuration present"
    else
        echo -e "${RED}✗${NC} Element Call configuration missing (required for group video)"
        ((ERRORS++))
    fi
fi

echo -e "\n${BLUE}8. Checking LiveKit SFU configuration...${NC}"

check_file_exists "livekit.yaml"

# Check LiveKit API key placeholder
if [[ -f "livekit.yaml" ]]; then
    if grep -q 'PLACEHOLDER_LIVEKIT_KEY' livekit.yaml 2>/dev/null; then
        echo -e "${GREEN}✓${NC} LiveKit API key placeholder present (will be generated by setup.sh)"
    elif grep -q 'keys:' livekit.yaml 2>/dev/null; then
        echo -e "${GREEN}✓${NC} LiveKit API keys configured"
    else
        echo -e "${RED}✗${NC} LiveKit API keys section missing"
        ((ERRORS++))
    fi

    if grep -q 'node_ip: "YOUR_IPV4"' livekit.yaml 2>/dev/null; then
        echo -e "${GREEN}✓${NC} LiveKit node_ip set to server IPv4 (YOUR_IPV4 placeholder)"
    else
        echo -e "${YELLOW}⚠${NC}  LiveKit node_ip not found or incorrect"
        ((WARNINGS++))
    fi
fi

# Check LiveKit in docker-compose
if grep -q "  livekit:" docker-compose.yml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Service defined: livekit"
else
    echo -e "${RED}✗${NC} Service missing: livekit (required for group video)"
    ((ERRORS++))
fi

if grep -q "  livekit-jwt:" docker-compose.yml 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Service defined: livekit-jwt"
else
    echo -e "${RED}✗${NC} Service missing: livekit-jwt (required for group video auth)"
    ((ERRORS++))
fi

# Check well-known rtc_foci
if [[ -f "wellknown/matrix/client" ]]; then
    if grep -q 'rtc_foci' wellknown/matrix/client 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Well-known client has rtc_foci (LiveKit SFU discovery)"
    else
        echo -e "${RED}✗${NC} Well-known client missing rtc_foci entry"
        ((ERRORS++))
    fi
fi

# Check LiveKit proxy in Caddyfile
if grep -q "livekit-sfu" Caddyfile 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Caddy configured to proxy LiveKit SFU"
else
    echo -e "${RED}✗${NC} Caddy missing LiveKit SFU proxy configuration"
    ((ERRORS++))
fi

if grep -q "lk-jwt" Caddyfile 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Caddy configured to proxy LiveKit JWT service"
else
    echo -e "${RED}✗${NC} Caddy missing LiveKit JWT service proxy"
    ((ERRORS++))
fi

# Summary
echo -e "\n${BLUE}=================================${NC}"
echo -e "${BLUE}Verification Summary${NC}"
echo -e "${BLUE}=================================${NC}"

if [[ $ERRORS -eq 0 && $WARNINGS -eq 0 ]]; then
    echo -e "${GREEN}✓ All checks passed!${NC}"
    echo -e "\nConfiguration is ready for deployment."
    echo -e "Run: ${GREEN}sudo ./setup.sh${NC} to deploy"
    exit 0
elif [[ $ERRORS -eq 0 ]]; then
    echo -e "${YELLOW}⚠ $WARNINGS warning(s) found${NC}"
    echo -e "\nConfiguration should work, but review warnings above."
    echo -e "Run: ${GREEN}sudo ./setup.sh${NC} to deploy"
    exit 0
else
    echo -e "${RED}✗ $ERRORS error(s) found${NC}"
    echo -e "${YELLOW}⚠ $WARNINGS warning(s) found${NC}"
    echo -e "\n${RED}Please fix the errors above before deploying.${NC}"
    exit 1
fi
